### ISSUE TITLE
Module not found: Error: Cannot resolve module 'async_hooks'

### ISSUE THREAD

**Issue by skibitsky** [scriptin/maruji#10]
Hey,

I tried to set up your app locally, but got an error.

Steps:
1. `npm i --legacy-peer-deps`
2. `npm run start`
3. Open `http://localhost:8080/webpack-dev-server/` in Safari

Full error message:
```
ERROR in ./~/bluebird/js/release/promise.js
Module not found: Error: Cannot resolve module 'async_hooks' in /Users/gleb/git/maruji/node_modules/bluebird/js/release
 @ ./~/bluebird/js/release/promise.js 34:4-26
```

macOS 13.0.1 
Node v16.19.0

**Comment by scriptin** [comment]
Hello @skibitsky! Thank you for your interest.

It has been a long time since I've done any work on this project, so most likely the configuration needs to be significantly updated. Some libraries are probably outdated and have missing dependencies. Although, [async_hooks is still there](https://www.npmjs.com/package/async_hooks), so I think it's an issue with dependency management configuration.

At this point, I think it's not worth investigating the root cause. It would probably be easier to rewrite this app from scratch (reusing some code from this repo) with the current versions of the libraries (especially new React). And I would not even use Bluebird, as Promises API has matured enough to make Bluebird unnecessary in this case.

My only recommendation is to try to update `bluebird` to [the latest version (v3.7.2)](https://www.npmjs.com/package/bluebird/v/3.7.2) and maybe try to use an older version of Node/NPM to prevent other potential issues. I recommend [NVM](https://github.com/nvm-sh/nvm) for managing Node versions. The version I've used when working on this (circa 2018) was most likely 8.x, 9.x or 10.x (I would try 8.x first).

**Comment by skibitsky** [comment]
Thank you, @scriptin! I will give it a try :)
